# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panic/Development/openups2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panic/Development/openups2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panic/Development/openups2/CMakeFiles /home/panic/Development/openups2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panic/Development/openups2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openups

# Build rule for target.
openups: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openups
.PHONY : openups

# fast build rule for target.
openups/fast:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/build
.PHONY : openups/fast

src/lib/HIDInterface.o: src/lib/HIDInterface.cpp.o

.PHONY : src/lib/HIDInterface.o

# target to build an object file
src/lib/HIDInterface.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDInterface.cpp.o
.PHONY : src/lib/HIDInterface.cpp.o

src/lib/HIDInterface.i: src/lib/HIDInterface.cpp.i

.PHONY : src/lib/HIDInterface.i

# target to preprocess a source file
src/lib/HIDInterface.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDInterface.cpp.i
.PHONY : src/lib/HIDInterface.cpp.i

src/lib/HIDInterface.s: src/lib/HIDInterface.cpp.s

.PHONY : src/lib/HIDInterface.s

# target to generate assembly for a file
src/lib/HIDInterface.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDInterface.cpp.s
.PHONY : src/lib/HIDInterface.cpp.s

src/lib/HIDOpenUPS2.o: src/lib/HIDOpenUPS2.cpp.o

.PHONY : src/lib/HIDOpenUPS2.o

# target to build an object file
src/lib/HIDOpenUPS2.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDOpenUPS2.cpp.o
.PHONY : src/lib/HIDOpenUPS2.cpp.o

src/lib/HIDOpenUPS2.i: src/lib/HIDOpenUPS2.cpp.i

.PHONY : src/lib/HIDOpenUPS2.i

# target to preprocess a source file
src/lib/HIDOpenUPS2.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDOpenUPS2.cpp.i
.PHONY : src/lib/HIDOpenUPS2.cpp.i

src/lib/HIDOpenUPS2.s: src/lib/HIDOpenUPS2.cpp.s

.PHONY : src/lib/HIDOpenUPS2.s

# target to generate assembly for a file
src/lib/HIDOpenUPS2.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/HIDOpenUPS2.cpp.s
.PHONY : src/lib/HIDOpenUPS2.cpp.s

src/lib/usbhid.o: src/lib/usbhid.cpp.o

.PHONY : src/lib/usbhid.o

# target to build an object file
src/lib/usbhid.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/usbhid.cpp.o
.PHONY : src/lib/usbhid.cpp.o

src/lib/usbhid.i: src/lib/usbhid.cpp.i

.PHONY : src/lib/usbhid.i

# target to preprocess a source file
src/lib/usbhid.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/usbhid.cpp.i
.PHONY : src/lib/usbhid.cpp.i

src/lib/usbhid.s: src/lib/usbhid.cpp.s

.PHONY : src/lib/usbhid.s

# target to generate assembly for a file
src/lib/usbhid.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/lib/usbhid.cpp.s
.PHONY : src/lib/usbhid.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/HArray.o: src/utils/HArray.cpp.o

.PHONY : src/utils/HArray.o

# target to build an object file
src/utils/HArray.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/HArray.cpp.o
.PHONY : src/utils/HArray.cpp.o

src/utils/HArray.i: src/utils/HArray.cpp.i

.PHONY : src/utils/HArray.i

# target to preprocess a source file
src/utils/HArray.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/HArray.cpp.i
.PHONY : src/utils/HArray.cpp.i

src/utils/HArray.s: src/utils/HArray.cpp.s

.PHONY : src/utils/HArray.s

# target to generate assembly for a file
src/utils/HArray.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/HArray.cpp.s
.PHONY : src/utils/HArray.cpp.s

src/utils/util.o: src/utils/util.cpp.o

.PHONY : src/utils/util.o

# target to build an object file
src/utils/util.cpp.o:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/util.cpp.o
.PHONY : src/utils/util.cpp.o

src/utils/util.i: src/utils/util.cpp.i

.PHONY : src/utils/util.i

# target to preprocess a source file
src/utils/util.cpp.i:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/util.cpp.i
.PHONY : src/utils/util.cpp.i

src/utils/util.s: src/utils/util.cpp.s

.PHONY : src/utils/util.s

# target to generate assembly for a file
src/utils/util.cpp.s:
	$(MAKE) -f CMakeFiles/openups.dir/build.make CMakeFiles/openups.dir/src/utils/util.cpp.s
.PHONY : src/utils/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... openups"
	@echo "... edit_cache"
	@echo "... src/lib/HIDInterface.o"
	@echo "... src/lib/HIDInterface.i"
	@echo "... src/lib/HIDInterface.s"
	@echo "... src/lib/HIDOpenUPS2.o"
	@echo "... src/lib/HIDOpenUPS2.i"
	@echo "... src/lib/HIDOpenUPS2.s"
	@echo "... src/lib/usbhid.o"
	@echo "... src/lib/usbhid.i"
	@echo "... src/lib/usbhid.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/HArray.o"
	@echo "... src/utils/HArray.i"
	@echo "... src/utils/HArray.s"
	@echo "... src/utils/util.o"
	@echo "... src/utils/util.i"
	@echo "... src/utils/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

